### ISSUE TITLE
Add support for NPM dependency checking

### ISSUE THREAD

**Issue by rcscott** [percipient/strongjobs#36]
It would be helpful to have functionality similar to the Python dependency checker but for NPM. Some of the implementation would overlap with https://github.com/percipient/strongjobs/blob/master/jobs/update-dependencies/update-python-dependencies.py, so some of that file would probably need to be pulled out into it's own abstract version that could then be used for both Python and NPM.

The `npm outdated` command may be helpful for this.

**Comment by rcscott** [comment]
@OllieBuilds this is the issue we were discussing.

**Comment by clokep** [comment]
Fixed by #37
